[package]
name = "rustineverything-module-blog"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack", "router"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
rustineverything-sdk = { path = "../../sdk" }
rustineverything-module-podcast = { path = "../podcast" }
pulldown-cmark = { version = "0.13.0", features = ["html"] }
pulldown-latex = "0.7.1"
serde_yaml = "0.9"
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"], optional = true }

[features]
server = ["dioxus/server", "dep:tokio"]
