[application]

[web.app]

# HTML title tag content
title = "Rust in Everything"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
[web.watcher]
reload_html = false
watch_path = ["src"]
ignore = ["public", "assets", "target", ".git", "node_modules"]
