[package]
name = "rustineverything-app"
version = "0.1.0"
authors = ["yuxuetr <54.yeying@gmail.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack", "html"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
# 核心库在前端不需要 server 特性
rustineverything-core = { path = "../core" }
rustineverything-widgets = { path = "../widgets" }
rustineverything-module-blog = { path = "../modules/blog" }
rustineverything-module-podcast = { path = "../modules/podcast" }
rustineverything-module-course = { path = "../modules/course" }
rustineverything-module-forum = { path = "../modules/forum" }
rustineverything-module-admin = { path = "../modules/admin" }
rustineverything-module-search = { path = "../modules/search" }
rustineverything-module-cases = { path = "../modules/cases" }
rustineverything-module-docs = { path = "../modules/docs" }
rustineverything-module-comments = { path = "../modules/comments" }
rustineverything-module-uploads = { path = "../modules/uploads" }
pulldown-cmark = "0.13.0"
chrono = { workspace = true, features = ["serde"] }

# 将以下依赖设为可选，仅供后端使用
tokio = { workspace = true, features = ["full"], optional = true }
axum = { version = "0.8", optional = true }
dotenvy = { version = "0.15", optional = true }
base64 = "0.22"
oauth2 = { workspace = true, optional = true }
tower-http = { version = "0.6", features = ["fs"], optional = true }
sea-orm = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
# 仅在 server 特性开启时，激活后端依赖和 core 的 server 特性
server = [
    "dioxus/server",
    "rustineverything-core/server",
    "rustineverything-widgets/server",
    "rustineverything-module-blog/server",
    "rustineverything-module-podcast/server",
    "rustineverything-module-course/server",
    "rustineverything-module-forum/server",
    "rustineverything-module-admin/server",
    "rustineverything-module-search/server",
    "rustineverything-module-cases/server",
    "rustineverything-module-docs/server",
    "rustineverything-module-comments/server",
    "rustineverything-module-uploads/server",
    "dep:tokio",
    "dep:axum",
    "dep:dotenvy",
    "dep:oauth2",
    "dep:tower-http",
    "dep:sea-orm",
    "dep:serde_yaml",
    "dep:rand",
]

[dev-dependencies]
tempfile = "3"
