[package]
name = "rustineverything-app"
version = "0.1.0"
authors = ["yuxuetr <54.yeying@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
# 核心库在前端不需要 server 特性
rustineverything-core = { path = "../core" }
rustineverything-module-blog = { path = "../modules/blog" }
pulldown-cmark = "0.13.0"
chrono = { workspace = true, features = ["serde"] }

# 将以下依赖设为可选，仅供后端使用
tokio = { workspace = true, features = ["full"], optional = true }
base64 = { version = "0.22", optional = true }
oauth2 = { version = "5.0.0", optional = true }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
# 仅在 server 特性开启时，激活后端依赖和 core 的 server 特性
server = [
    "dioxus/server",
    "rustineverything-core/server",
    "dep:tokio",
    "dep:base64",
    "dep:oauth2",
]
