// Writes crates/app/tailwind-sources.css: one `@source` line per Rust UI crate
// whose class names Tailwind must scan. The crate source lives in the cargo
// registry, whose path differs per machine and inside Docker, so the line is
// generated at build time instead of committed (dioxus-ui FB-01).
//
// Fails when a crate is missing: a stylesheet built without the line has no
// component styles and gives no error.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const UI_CRATES = ['dioxus-shadcn'];

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(repoRoot, 'crates/app/tailwind-sources.css');

const metadata = JSON.parse(
  execFileSync('cargo', ['metadata', '--format-version', '1', '--locked'], {
    cwd: repoRoot,
    maxBuffer: 256 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'inherit'],
  }),
);

const lines = UI_CRATES.map((name) => {
  const pkg = metadata.packages.find((p) => p.name === name);
  if (!pkg) {
    console.error(`tw-sources: crate ${name} is not in the dependency graph`);
    process.exit(1);
  }
  return `@source "${join(dirname(pkg.manifest_path), 'src')}";`;
});

writeFileSync(outFile, `/* Generated by scripts/tw-sources.mjs. Do not edit. */\n${lines.join('\n')}\n`);
console.log(`tw-sources: wrote ${outFile}`);
