[package]
name = "rustineverything-core"
version = "0.1.0"
authors = ["yuxuetr <54.yeying@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { workspace = true, optional = true, features = ["fullstack"] }
tokio = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
wasmi.workspace = true
sea-orm = { workspace = true, optional = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
chrono = { workspace = true, features = ["serde"] }
rustineverything-sdk = { path = "../sdk" }
serde_yaml = { workspace = true }
oauth2 = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
jsonwebtoken = { workspace = true, optional = true }
aes-gcm = { workspace = true, optional = true }
tracing = { workspace = true }
async-trait = { version = "0.1", optional = true }

[features]
server = ["dep:dioxus", "dep:tokio", "dep:sea-orm", "dep:oauth2", "dep:reqwest", "dep:sha2", "dep:base64", "dep:rand", "dep:jsonwebtoken", "dep:aes-gcm", "dep:async-trait"]

[dev-dependencies]
tempfile = "3"
mockito = "1.5"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15"
